name: Build Android Native Libraries (Multi-Arch)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'lua/**'
      - 'zlib/**'
      - 'libjuice/**'

jobs:
  build-libs:
    strategy:
      matrix:
        arch:
          - name: x86_64
            runner: ubuntu-24.04
            image: termux/termux-docker:x86_64
          - name: aarch64
            runner: ubuntu-24.04-arm
            image: termux/termux-docker:aarch64

    name: Build on ${{ matrix.arch.name }}
    runs-on: ${{ matrix.arch.runner }}
    container:
      image: ${{ matrix.arch.image }}
      volumes:
        - /tmp/node20:/__e/node20
    env:
      ANDROID_ROOT: /system
      ANDROID_DATA: /data
      PREFIX: /data/data/com.termux/files/usr
      HOME: /data/data/com.termux/files/home
      PATH: /data/data/com.termux/files/usr/bin
      TMPDIR: /data/data/com.termux/files/usr/tmp
      LANG: en_US.UTF-8
      TZ: UTC

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Termux environment
        run: |
          ln -sf ${PREFIX}/etc/termux/mirrors/default ${PREFIX}/etc/termux/chosen_mirrors
          /entrypoint.sh bash -c "yes | pkg upgrade -y"
          chmod -R o+x ${PREFIX}/bin

      - name: Build Lua
        run: |
          cd lua
          /entrypoint.sh make linux -j8

      - name: Upload Lua artifact
        uses: actions/upload-artifact@v4
        with:
          name: lua-${{ matrix.arch.name }}
          path: lua/*.a

      - name: Build Zlib
        run: |
          cd zlib
          /entrypoint.sh make -j8

      - name: Upload Zlib artifact
        uses: actions/upload-artifact@v4
        with:
          name: zlib-${{ matrix.arch.name }}
          path: zlib/*.a

      - name: Build Libjuice
        run: |
          cd libjuice
          /entrypoint.sh make -j8

      - name: Upload Libjuice artifact
        uses: actions/upload-artifact@v4
        with:
          name: libjuice-${{ matrix.arch.name }}
          path: libjuice/*.a